version: "3"

services:
  database:
    build: ./dockerdatabase
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  backend:
    build: ./dockerbackend
    ports:
      - "8080:8080"
    volumes:
      - ./dockerbackend:/app
    environment:
      - DB_HOST=database
    depends_on:
      - database

  frontend:
    build: ./dockerfrontend
    ports:
      - "5000:5000"
    volumes:
      - ./dockerfrontend:/app
    depends_on:
      - backend

volumes:
  db-data:

